### ISSUE TITLE
Is there a way to pause and resume a workflow?

### ISSUE THREAD

**Issue by panesofglass** [aleph2c/miros#4]
I'm interested in exposing transitions as links in a web app, but I cannot find any examples after a quick glance that would indicate whether or not miros allows for pausing and resuming workflows. Does miros allow for this use case?

**Comment by aleph2c** [comment]
The pause that you are looking for could be handled by breaking a transition down into two steps.  An event which would have caused your original transition could be caught by [a hook](https://aleph2c.github.io/miros/html/recipes.html#hooks), then the chart could post an event to itself using a deferred [one-shot event](https://aleph2c.github.io/miros/html/recipes.html#creating-a-one-shot-event).  This second event could be caught by your state and cause the transition.

You could program the delay in your one-shot however you like.

Make sure that you [cancel the one shot](https://aleph2c.github.io/miros/html/recipes.html#canceling-event-source-by-signal-name) upon exiting your state, otherwise you will end up with strange and unexpected behaviors.

You could repeat this approach for each state for which you want a delay.
